### ISSUE TITLE
AttributeError: type object 'thybolt' has no attribute 'preamble_detector_bp'

### ISSUE THREAD

**Issue by janvgils** [thybolt4hams/gr-thybolt#1]
Running the gnuradio thybolt flowgraph I get the error `AttributeError: type object 'thybolt' has no attribute 'preamble_detector_bp'` 

Here some more details on the system. 

Running on 

```
cat /etc/os-release 

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

gnuradio-config-info  -v
3.8.2.0
```

Successfully build and installed

```
sudo make install
[ 22%] Built target gnuradio-thybolt
[ 22%] Built target pygen_apps_9a6dd
[ 22%] Built target thybolt_swig_swig_doc
[ 33%] Built target thybolt_swig_swig_compilation
[ 55%] Built target thybolt_swig
[ 77%] Built target pygen_swig_ee76a
[100%] Built target pygen_python_f6df7
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/lib/cmake/thybolt/thyboltConfig.cmake
-- Up-to-date: /usr/local/include/thybolt/api.h
-- Up-to-date: /usr/local/include/thybolt/preamble_detector_bp.h
-- Installing: /usr/local/lib/x86_64-linux-gnu/libgnuradio-thybolt.so.1.0.0.0
-- Up-to-date: /usr/local/lib/x86_64-linux-gnu/libgnuradio-thybolt.so.1.0.0
-- Up-to-date: /usr/local/lib/x86_64-linux-gnu/libgnuradio-thybolt.so
-- Installing: /usr/local/lib/cmake/thybolt/gnuradio-thyboltTargets.cmake
-- Installing: /usr/local/lib/cmake/thybolt/gnuradio-thyboltTargets-release.cmake
-- Installing: /usr/local/lib/cmake/thybolt/gnuradio-thyboltConfig.cmake
-- Installing: /usr/local/lib/python3/dist-packages/thybolt/_thybolt_swig.so
-- Set runtime path of "/usr/local/lib/python3/dist-packages/thybolt/_thybolt_swig.so" to ""
-- Installing: /usr/local/lib/python3/dist-packages/thybolt/thybolt_swig.py
-- Installing: /usr/local/lib/python3/dist-packages/thybolt/thybolt_swig.pyc
-- Installing: /usr/local/lib/python3/dist-packages/thybolt/thybolt_swig.pyo
-- Up-to-date: /usr/local/include/thybolt/thybolt/swig/thybolt_swig.i
-- Installing: /usr/local/include/thybolt/thybolt/swig/thybolt_swig_doc.i
-- Up-to-date: /usr/local/lib/python3/dist-packages/thybolt/__init__.py
-- Installing: /usr/local/lib/python3/dist-packages/thybolt/__init__.pyc
-- Installing: /usr/local/lib/python3/dist-packages/thybolt/__init__.pyo
-- Up-to-date: /usr/local/share/gnuradio/grc/blocks/thybolt_preamble_detector_bp.block.yml

sudo ldconfig

```
![image](https://user-images.githubusercontent.com/21240133/207698252-2b20d75e-1aab-455b-83e5-c1fe0825d4d7.png)

Using the following grc file: [thybolt.grc.zip](https://github.com/thybolt4hams/gr-thybolt/files/10231081/thybolt.grc.zip)
```
Executing: /usr/bin/python3 -u tmp/THYBOLT/thybolt.py

Traceback (most recent call last):
  File "tmp/THYBOLT/thybolt.py", line 287, in <module>
    main()
  File "tmp/THYBOLT/thybolt.py", line 263, in main
    tb = top_block_cls()
  File "tmp/THYBOLT/thybolt.py", line 102, in __init__
    self.thybolt_preamble_detector_bp_0 = thybolt.preamble_detector_bp(510)
AttributeError: type object 'thybolt' has no attribute 'preamble_detector_bp'
```
But there seems to be an error with the gr-thybolt OOT

**Comment by thybolt4hams** [comment]
Hi, 

Thank you for taking the time and posting the issue. we ran the GRC file you uploaded and we are able to run it without any issues just by changing the input .wav file. 

The error you are facing commonly occurs when you miss installing a module called 'SWIG'. Preinstalled blocks in GNURadio work without SWIG dependency, but if you are installing an OOT Block, there is a good chance you will see the error if you have SWIG missing from your libraries. Please try installing SWIG and see if it solves the error. For your reference, we are using SWIG version 4.0.2

As you have posted your system details, we are trying to reproduce the same error by configuring a system same to yours. Will share any info if we are able to resolve it on our end. Thank you

**Comment by janvgils** [comment]
Thank you team,

If swig wasn't available the build and installation of the OOT module wouldn't be possible.

But as you can see below the `swig module` is installed.

```
dpkg -l | grep -i swig
ii  swig                                   4.0.2-1                        all          Generate scripting interfaces to C/C++ code
ii  swig4.0                                4.0.2-1                        amd64        Generate scripting interfaces to C/C++ code
```

**Comment by thybolt4hams** [comment]
Hi Jan, 

we configured a fresh system similar to yours mentioned in above comment and installed gnuradio-v3.8 , gr-thybolt and unfortunately we were not able to reproduce the error you encountered. we used the same system to decode PDOT satellite's telemetry as well without issue. we worked on the same grc flowgraph you shared as well with an IQ sample from one of our recent tracking. 

I am adding the system configuration below. 
<pre>
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

gnuradio-config-info -v
v3.8.5.0-6-g57bd109d
</pre>

Can you please try and reinstall the module and see if it helps. Let us know if you had any luck. Thank you

**Comment by janvgils** [comment]
Good day,

By changing the flow graph Title from thybolt to thybolt_decoder I no longer have a problem running the flow graph.

![image](https://user-images.githubusercontent.com/21240133/210951533-51b5d562-2174-470e-8586-22c19daa1a3e.png)

Now I am only running into an issue that the "Wav File Source" isn't playing the full length of IQ file and the replay option is also not working.

So one small step forward and another new challenge.
